version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - "127.0.0.1:${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  adminer:
    image: adminer
    ports:
      - "127.0.0.1:${ADMINER_PORT}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=database
    links:
      - postgres:database
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}