version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - "127.0.0.1:${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
